scikit-learn-contrib/imbalanced-learn

- README.md
- unbalanced_dataset/over_sampling.py
Hi Fernando,
I update the with the link to the article and the year of publication.
I also added a new variant for random over sampling by generated samples based on the minority one with an additional Gaussian noise.
Cheers,
> Update the README

- unbalanced_dataset/over_sampling.py
Make the ratio parameter be more understandable.
> Add detailed documentation to OverSampler

- README.md
This grants some advantages such being able to list the package in the `requirements.txt` and use it in continuous integration builds, also, it's a cleaner way.
> Add pip installation method

- examples/under-sampling/plot_repeated_edited_nearest_neighbours.py
- unbalanced_dataset/under_sampling/__init__.py
- unbalanced_dataset/under_sampling/edited_nearest_neighbours.py
It would be interesting to change the dataset used in the example so that the differences can be more visual, but the 'verbose' parameter allows us to see that RENN has a higher reduction power than ENN.
> RENN - Repeated Edited Nearest Neighbors undersampling method

- examples/under-sampling/plot_repeated_edited_nearest_neighbours.py
In `plot_repeated_edited_nearest_neighbours.py` there are calls to fit_transform method instead of the new fit_sample.
Regards,
Chris
> Replace fit_transform method with the new fit_sample API

- imblearn/pipeline.py
- imblearn/version.py
Remove any mentions of unbalanced_dataset in docs
> Remove any mentions of unbalanced_dataset in docs

- examples/datasets/plot_make_imbalance.py
- imblearn/datasets/__init__.py
- imblearn/datasets/imbalance.py
- imblearn/datasets/tests/test_make_imbalance.py
function `make_imbalance` to help artificially generate imbalance data from a given dataset.
This might be helpful for experiments, and for our toy problems and experiments.
included tests and example (image bellow).
> [MRG] adding make_imbalance function

- doc/api.rst
- imblearn/datasets/imbalance.py
It is the missing part from PR #115 
@dvro I forgot something at that time. How shall we handle if the dataset is multiclass? Do we consider to reduce only the number of samples in the minority class?
> [MRG] Make imbalance

- imblearn/datasets/__init__.py
- imblearn/datasets/imbalance.py
- imblearn/datasets/tests/test_make_imbalance.py
- imblearn/ensemble/balance_cascade.py
- imblearn/under_sampling/condensed_nearest_neighbour.py
- imblearn/under_sampling/edited_nearest_neighbours.py
- imblearn/under_sampling/instance_hardness_threshold.py
- imblearn/under_sampling/nearmiss.py
- imblearn/under_sampling/neighbourhood_cleaning_rule.py
- imblearn/under_sampling/one_sided_selection.py
- imblearn/under_sampling/tomek_links.py
> [MRG] Address #131 - Replace nonzero by flatnonzero whenever possible

- doc/whats_new.rst
- imblearn/under_sampling/edited_nearest_neighbours.py
- imblearn/under_sampling/tests/test_allknn.py
@dvro @chkoar If you could check into details the two criteria that I added.
> [MRG] Address issue #130 - Add specific stopping criteria for the AllKNN

- doc/whats_new.rst
- imblearn/under_sampling/condensed_nearest_neighbour.py
> [MRG] Address issue #137 - Error of the indices return by CNN

- imblearn/under_sampling/nearmiss.py
> [MRG] Address issue #140 - Add condition to raise warning in NearMiss

- doc/whats_new.rst
- imblearn/ensemble/balance_cascade.py
> [MRG] Address issue #142 - Solve problem with max subset to one in BC

- imblearn/pipeline.py
- imblearn/tests/test_pipeline.py
The purpose of the Pipeline class it was to provide a simple object that will perform linear transformations using transformers and samplers.
This PR adds some validation checks and raises errors if there is a violation of the following rules:
* All intermediate estimators should not implement both sample and transform methods
* All intermediate estimators should not be or inherit from the Pipeline class
> [MRG+1] Extra validation checks in Pipeline object

- imblearn/ensemble/balance_cascade.py
- imblearn/ensemble/tests/test_balance_cascade.py
- imblearn/under_sampling/instance_hardness_threshold.py
- imblearn/under_sampling/tests/test_instance_hardness_threshold.py
Whenever possible, pass a classifier estimator instead of a string to be more flexible through experiments.
> [MRG] ENH: Pass a classifier object instead of string

- imblearn/over_sampling/smote.py
- imblearn/over_sampling/tests/test_smote.py
- imblearn/pipeline.py
- imblearn/under_sampling/cluster_centroids.py
- imblearn/under_sampling/condensed_nearest_neighbour.py
- imblearn/under_sampling/one_sided_selection.py
- imblearn/under_sampling/tests/test_cluster_centroids.py
- imblearn/under_sampling/tests/test_condensed_nearest_neighbour.py
- imblearn/under_sampling/tests/test_one_sided_selection.py
> [MRG] ENH: Remove **kwargs

- imblearn/under_sampling/condensed_nearest_neighbour.py
Fixes #208 
It seems, that np.squeeze was redundant, when idx_maj_sample is only one element, it makes S_x 1 dimensional and causes error
> [MRG] CondensedNearestNeighbour ValueError fix #208

- doc/api.rst
- doc/whats_new.rst
- imblearn/__init__.py
- imblearn/metrics/__init__.py
- imblearn/metrics/classification.py
- imblearn/metrics/tests/test_classification.py
- imblearn/metrics/tests/test_score_objects.py
- imblearn/setup.py
Address issue #152 
There some metrics which are not implemented in scikit-learn but that are usually used for the evaluation on imbalanced set:
There already some implementation [there](https://github.com/glemaitre/protoclass/blob/master/protoclass/validation/metric.py) which could be put together to fit the scikit-learn API
There is a need for:
> [MRG] EHN new metrics

- doc/api.rst
- examples/applications/plot_multi_class_under_sampling.py
- examples/datasets/README.txt
- examples/evaluation/plot_classification_report.py
- examples/evaluation/plot_metrics.py
- examples/model_selection/plot_validation_curve.py
- imblearn/metrics/classification.py
> [MRG] Example for JMLR

- examples/datasets/plot_make_imbalance.py
- examples/under-sampling/plot_allknn.py
- examples/under-sampling/plot_instance_hardness_threshold.py
- examples/under-sampling/plot_repeated_edited_nearest_neighbours.py
> MAINT Improve examples - issue #216

- imblearn/metrics/classification.py
- imblearn/metrics/tests/test_classification.py
Fixes #215
Adds the possibility of calculating G-mean for multi-class problems without resorting to averaging binary G-mean values. At the same time G-mean can still be average on a class-wise basis. This implementation also adds the possibility of "correcting" unrecognized class recalls from zero to a user-specified value. This is only works when `average == 'multiclass'`.
In the `report_imbalanced_multiclass()` I left the resulting report as it was, since it is designed to show the results separately for each class. You may, however, consider to extend this report to have a header with overall accuracy and overall G-mean (as single lines above the table). I'm not sure if you want to add that, especially that accuracy works a little bit differently than the measures you implemented in …
> Addressing issue #215 - G-mean for multi-class problems

- imblearn/under_sampling/one_sided_selection.py
- imblearn/under_sampling/tests/test_one_sided_selection.py
With current implementation idx_under is concatenated with idx_under,
idx_maj_sample and idx_tmp. And idx_maj_sample is created with
indices of majority class so wrong indices will be created.
This patch fixes the way of creating idx_under.
> [MRG+1] idx_under should be expressed by indices of parameter X

- imblearn/under_sampling/tomek_links.py
The variable "count" is NOT used in tomek_links.py. So this patch
removed it as a minor refactoring.
> [MRG] Remove unused variable

- imblearn/over_sampling/adasyn.py
Changed n_neighbours to n_neighbors in Parameters description
Just spelling of parameter n_neighbors is corrected. Previously it was n_neighbours in Parameter description. It was confusion to me, when I wanted to use the params in GridSearch. And used the parameters from the description.
> Changed n_neighbours to n_neighbors

- doc/whats_new.rst
- imblearn/under_sampling/neighbourhood_cleaning_rule.py
- imblearn/under_sampling/tests/test_neighbourhood_cleaning_rule.py
Fixed: for misclassified positive samples they are returned themselves but not their negative neighbours (so behaviour for positive result of IF statement is wrong). #227
> NeighbourhoodCleaningRule fix

- imblearn/ensemble/easy_ensemble.py
In EasyEnsemble doc page, its signature is
> class imblearn.ensemble.EasyEnsemble(ratio='auto', return_indices=False, random_state=None, replacement=False, n_subsets=10)
with `return_indices=False`, but its pydoc says
> return_indices : bool, optional (default=True)
>
>Whether or not to return the indices of the samples randomly selected from the majority class.
Checking the code at https://github.com/scikit-learn-contrib/imbalanced-learn/blob/b45a3e4167d188ec9fd40afd3a56330aa80a5ee1/imblearn/ensemble/easy_ensemble.py#L92, the correct value is False.
> [MRG] Correcting EasyEnsemble doc

- doc/whats_new.rst
- imblearn/pipeline.py
- imblearn/tests/test_pipeline.py
Fixes #226 
`Pipeline` should allow `None` objects in prepossessing steps. With this modification 
one could use `*SearchCV` estimators and examine if the performance of the final 
classifier is improved by using a sampler or not.
> Allow None objects in Pipeline chain

- doc/conf.py
Fixes #251
Should make link clickable in the doc.
> [MRG] FIX/DOC make link clickable

- doc/_static/css/imbalanced-learn.css
The #262 made the links to be underlined everywhere. With this fix only the reference links are underlined and only in the code section of examples
> DOC: Style the links so they stand out only in examples

- README.rst
- doc/about.rst
> [MRG] DOC Update README

- imblearn/pipeline.py
- imblearn/tests/test_pipeline.py
Fixed #280 
Allow for caching Transformer and Sampler within a Pipeline.
> [MRG] ENH Cache enabling in Pipeline

- imblearn/combine/smote_enn.py
- imblearn/combine/smote_tomek.py
- imblearn/ensemble/balance_cascade.py
- imblearn/ensemble/easy_ensemble.py
- imblearn/over_sampling/adasyn.py
- imblearn/over_sampling/random_over_sampler.py
- imblearn/over_sampling/smote.py
- imblearn/under_sampling/prototype_generation/cluster_centroids.py
- imblearn/under_sampling/prototype_selection/condensed_nearest_neighbour.py
- imblearn/under_sampling/prototype_selection/edited_nearest_neighbours.py
- imblearn/under_sampling/prototype_selection/instance_hardness_threshold.py
- imblearn/under_sampling/prototype_selection/neighbourhood_cleaning_rule.py
- imblearn/under_sampling/prototype_selection/one_sided_selection.py
- imblearn/under_sampling/prototype_selection/random_under_sampler.py
- imblearn/under_sampling/prototype_selection/tomek_links.py
Partially addressing #303
Mentioning in the docstring which type of multi-class scheme is used.
We need to add more information in the User Guide which is coming.
> [MRG] DOC mention the multi-class scheme used

- imblearn/under_sampling/prototype_selection/edited_nearest_neighbours.py
- imblearn/under_sampling/prototype_selection/tests/test_allknn.py
Sometime it could be useful to be a bit more tolerant
> [MRG] EHN allow to become minority in AllKNN

- doc/whats_new.rst
- imblearn/utils/tests/test_validation.py
- imblearn/utils/validation.py
closes #305 
Allow to pass argument to ratio when this is a function.
It could be useful when the heuristic is outside of the function
> [MRG] FIX/TST pass argument to ratio as callable

- imblearn/combine/tests/test_smote_enn.py
- imblearn/combine/tests/test_smote_tomek.py
- imblearn/datasets/tests/test_imbalance.py
- imblearn/datasets/tests/test_zenodo.py
- imblearn/ensemble/tests/test_balance_cascade.py
- imblearn/ensemble/tests/test_easy_ensemble.py
- imblearn/metrics/tests/test_classification.py
- imblearn/over_sampling/tests/test_adasyn.py
- imblearn/over_sampling/tests/test_random_over_sampler.py
- imblearn/over_sampling/tests/test_smote.py
- imblearn/tests/test_common.py
- imblearn/tests/test_pipeline.py
- imblearn/under_sampling/prototype_generation/tests/test_cluster_centroids.py
- imblearn/under_sampling/prototype_selection/tests/test_allknn.py
- imblearn/under_sampling/prototype_selection/tests/test_condensed_nearest_neighbour.py
- imblearn/under_sampling/prototype_selection/tests/test_edited_nearest_neighbours.py
- imblearn/under_sampling/prototype_selection/tests/test_instance_hardness_threshold.py
- imblearn/under_sampling/prototype_selection/tests/test_nearmiss.py
- imblearn/under_sampling/prototype_selection/tests/test_one_sided_selection.py
- imblearn/under_sampling/prototype_selection/tests/test_random_under_sampler.py
- imblearn/under_sampling/prototype_selection/tests/test_repeated_edited_nearest_neighbours.py
- imblearn/under_sampling/prototype_selection/tests/test_tomek_links.py
- imblearn/utils/estimator_checks.py
- imblearn/utils/tests/test_estimator_checks.py
- imblearn/utils/tests/test_validation.py
> [MRG] nosetests to pytests

- doc/developers_utils.rst
- doc/user_guide.rst
@glemaitre which functions should be documented here?
> [MRG] Add development doc

- doc/developers_utils.rst
> [MRG]fix minor errors in developer's utils

- doc/developers_utils.rst
- imblearn/combine/tests/test_smote_enn.py
- imblearn/combine/tests/test_smote_tomek.py
- imblearn/datasets/tests/test_imbalance.py
- imblearn/datasets/tests/test_zenodo.py
- imblearn/ensemble/tests/test_balance_cascade.py
- imblearn/metrics/tests/test_classification.py
- imblearn/over_sampling/tests/test_adasyn.py
- imblearn/over_sampling/tests/test_smote.py
- imblearn/tests/test_exceptions.py
- imblearn/tests/test_pipeline.py
- imblearn/under_sampling/prototype_generation/tests/test_cluster_centroids.py
- imblearn/under_sampling/prototype_selection/tests/test_allknn.py
- imblearn/under_sampling/prototype_selection/tests/test_condensed_nearest_neighbour.py
- imblearn/under_sampling/prototype_selection/tests/test_edited_nearest_neighbours.py
- imblearn/under_sampling/prototype_selection/tests/test_instance_hardness_threshold.py
- imblearn/under_sampling/prototype_selection/tests/test_nearmiss.py
- imblearn/under_sampling/prototype_selection/tests/test_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/prototype_selection/tests/test_one_sided_selection.py
- imblearn/under_sampling/prototype_selection/tests/test_repeated_edited_nearest_neighbours.py
- imblearn/utils/estimator_checks.py
- imblearn/utils/testing.py
- imblearn/utils/tests/test_deprecation.py
- imblearn/utils/tests/test_estimator_checks.py
- imblearn/utils/tests/test_testing.py
- imblearn/utils/tests/test_validation.py
Partial migration from nose to pytest (see #323)
Things related to raising. The idea is to migrate or change the following: 
~* [ ] `from sklearn.utils.testing import assert_no_warnings`~
Without touching any testing logic. 
Do not squash this PR (I've reworked the git history for easier inspection). And I would recommend to review each commit of the PR independently.
> [MRG] Migrate raising errors from nose to pytest

- doc/combine.rst
I just noticed the new release and was reading through the new documentation, which is really awesome! While reading, I found the description on combining under- and over-sampling methods a bit hard to read due to some minor typos and though rephrasing it a bit would help.
> Minor rephrasing in the combine doc

- imblearn/under_sampling/prototype_selection/neighbourhood_cleaning_rule.py
> [WIP] DOC add threshold_cleaning in NCR

- imblearn/utils/estimator_checks.py
> [MRG] TST remove double check of sciki-learn estimator

- doc/under_sampling.rst
- examples/under-sampling/plot_illustration_tomek_links.py
- imblearn/base.py
- imblearn/combine/smote_enn.py
- imblearn/combine/smote_tomek.py
- imblearn/ensemble/balance_cascade.py
- imblearn/ensemble/easy_ensemble.py
- imblearn/over_sampling/adasyn.py
- imblearn/over_sampling/base.py
- imblearn/over_sampling/random_over_sampler.py
- imblearn/over_sampling/smote.py
- imblearn/under_sampling/prototype_generation/cluster_centroids.py
- imblearn/under_sampling/prototype_selection/condensed_nearest_neighbour.py
- imblearn/under_sampling/prototype_selection/edited_nearest_neighbours.py
- imblearn/under_sampling/prototype_selection/instance_hardness_threshold.py
- imblearn/under_sampling/prototype_selection/nearmiss.py
- imblearn/under_sampling/prototype_selection/neighbourhood_cleaning_rule.py
- imblearn/under_sampling/prototype_selection/one_sided_selection.py
- imblearn/under_sampling/prototype_selection/random_under_sampler.py
- imblearn/under_sampling/prototype_selection/tests/test_allknn.py
- imblearn/under_sampling/prototype_selection/tests/test_edited_nearest_neighbours.py
- imblearn/under_sampling/prototype_selection/tests/test_nearmiss.py
- imblearn/under_sampling/prototype_selection/tests/test_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/prototype_selection/tests/test_repeated_edited_nearest_neighbours.py
- imblearn/under_sampling/prototype_selection/tests/test_tomek_links.py
- imblearn/under_sampling/prototype_selection/tomek_links.py
- imblearn/utils/deprecation.py
- imblearn/utils/estimator_checks.py
- imblearn/utils/tests/test_validation.py
- imblearn/utils/validation.py
closes #344 
closes: #365 
Remove the fixed random_seed to compute the hash. Instead we pick-up equally spaced samples.
Since this is related, random_state has been deprecated whenever possible.
TODO:
> [MRG] MAINT make hash deterministic

- imblearn/base.py
- imblearn/tests/test_common.py
The logger in the `SamplerMixin` it was defined as `logging.getLogger(__name__)`. This has the side effect that all logging it is performed under the logger name `imblearn.base`. With the proposed approach the logger of a method it is named with the full module name in which the method belongs. 
We probably need a test for that change.
> [MRG] Fix logger name

- doc/whats_new/v0.0.4.rst
- imblearn/__init__.py
- imblearn/base.py
- imblearn/combine/smote_enn.py
- imblearn/combine/smote_tomek.py
- imblearn/ensemble/balance_cascade.py
- imblearn/ensemble/base.py
- imblearn/utils/estimator_checks.py
- imblearn/utils/tests/test_validation.py
- imblearn/utils/validation.py
This PR allows user to provide targets which are one-vs-all encoded.
This is widely used in Keras for the loss function.
This is part of #409
> EHN accept one-vs-all encoding for labels

- README.rst
- references.bib
- fix typo and errors in references
- add pdf link in references
- add references.bib
- add bib link in references
bib file processed with bibtool
> DOC fix typo in ref, add pdf link to ref and add references.bib

- .gitignore
- imblearn/combine/smote_enn.py
- imblearn/combine/smote_tomek.py
- imblearn/ensemble/balance_cascade.py
- imblearn/ensemble/easy_ensemble.py
- imblearn/over_sampling/adasyn.py
- imblearn/over_sampling/random_over_sampler.py
- imblearn/over_sampling/smote.py
- imblearn/under_sampling/prototype_generation/cluster_centroids.py
- imblearn/under_sampling/prototype_selection/condensed_nearest_neighbour.py
- imblearn/under_sampling/prototype_selection/edited_nearest_neighbours.py
- imblearn/under_sampling/prototype_selection/instance_hardness_threshold.py
- imblearn/under_sampling/prototype_selection/nearmiss.py
- imblearn/under_sampling/prototype_selection/neighbourhood_cleaning_rule.py
- imblearn/under_sampling/prototype_selection/one_sided_selection.py
- imblearn/under_sampling/prototype_selection/random_under_sampler.py
- imblearn/under_sampling/prototype_selection/tomek_links.py
Just fixing the spelling of "multi".
Issue: https://github.com/scikit-learn-contrib/imbalanced-learn/issues/430
> [MRG] Consistent spelling error in documentation

- doc/whats_new/v0.0.4.rst
- imblearn/over_sampling/random_over_sampler.py
- imblearn/over_sampling/tests/test_random_over_sampler.py
As in RandomUnderSampler, this commit adds the option to return the indices used for over sampling in the corresponding classes. This can be useful, for example, if the same sampling is to be used again in a different data structure with the original shape and class distribution.
> Add option to return indices in RandomOverSampler

- doc/whats_new/v0.0.4.rst
- imblearn/over_sampling/adasyn.py
- imblearn/over_sampling/smote.py
- imblearn/under_sampling/prototype_generation/cluster_centroids.py
- imblearn/utils/estimator_checks.py
> BUG: Preserve dtype of X and y when generating samples

- doc/whats_new/v0.0.4.rst
- imblearn/base.py
- imblearn/combine/_smote_enn.py
- imblearn/combine/_smote_tomek.py
- imblearn/ensemble/_balance_cascade.py
- imblearn/ensemble/_easy_ensemble.py
- imblearn/over_sampling/_adasyn.py
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/under_sampling/_prototype_generation/_cluster_centroids.py
- imblearn/under_sampling/_prototype_selection/_condensed_nearest_neighbour.py
- imblearn/under_sampling/_prototype_selection/_edited_nearest_neighbours.py
- imblearn/under_sampling/_prototype_selection/_instance_hardness_threshold.py
- imblearn/under_sampling/_prototype_selection/_nearmiss.py
- imblearn/under_sampling/_prototype_selection/_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/_prototype_selection/_one_sided_selection.py
- imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
- imblearn/under_sampling/_prototype_selection/_tomek_links.py
> DOC: Remove docstring which are not useful

- doc/whats_new/v0.0.4.rst
- imblearn/pipeline.py
- imblearn/tests/test_pipeline.py
Adds the ability to pass a joblib.Memory object to the `make_pipeline` function.
> Add memory to make_pipeline function

- doc/whats_new/v0.0.4.rst
A couple of entries refer to wrong PRs
> Fix whats new entries

- doc/whats_new/v0.0.4.rst
- imblearn/combine/tests/test_smote_enn.py
- imblearn/combine/tests/test_smote_tomek.py
- imblearn/datasets/tests/test_imbalance.py
- imblearn/datasets/tests/test_zenodo.py
- imblearn/ensemble/tests/test_balance_cascade.py
- imblearn/keras/tests/test_generator.py
- imblearn/metrics/tests/test_classification.py
- imblearn/metrics/tests/test_score_objects.py
- imblearn/over_sampling/tests/test_adasyn.py
- imblearn/over_sampling/tests/test_random_over_sampler.py
- imblearn/over_sampling/tests/test_smote.py
- imblearn/tensorflow/tests/test_generator.py
- imblearn/under_sampling/_prototype_generation/_cluster_centroids.py
- imblearn/under_sampling/_prototype_generation/tests/test_cluster_centroids.py
- imblearn/under_sampling/_prototype_selection/_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/_prototype_selection/_tomek_links.py
- imblearn/under_sampling/_prototype_selection/tests/test_allknn.py
- imblearn/under_sampling/_prototype_selection/tests/test_condensed_nearest_neighbour.py
- imblearn/under_sampling/_prototype_selection/tests/test_edited_nearest_neighbours.py
- imblearn/under_sampling/_prototype_selection/tests/test_instance_hardness_threshold.py
- imblearn/under_sampling/_prototype_selection/tests/test_nearmiss.py
- imblearn/under_sampling/_prototype_selection/tests/test_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/_prototype_selection/tests/test_one_sided_selection.py
- imblearn/under_sampling/_prototype_selection/tests/test_random_under_sampler.py
- imblearn/under_sampling/_prototype_selection/tests/test_repeated_edited_nearest_neighbours.py
- imblearn/under_sampling/_prototype_selection/tests/test_tomek_links.py
- imblearn/utils/tests/test_docstring.py
> TST: refactor and pytest style

- doc/ensemble.rst
- imblearn/ensemble/_forest.py
- setup.cfg
min_samples_leaf and min_weight_sample_leaf have been undeprecated in scikit-learn.
We revert the changes in those parameters to have the same behavior.
> MAINT: revert the deprecation of forest parameter to sync with sklearn

- doc/whats_new/v0.0.4.rst
- imblearn/over_sampling/_smote.py
> FIX: SMOTENC should use half of the median of the std. dev.

- doc/whats_new/v0.4.rst
- imblearn/over_sampling/_smote.py
> [WIP] FIX: avoid densifying sparse matrix before inverse_transform of OHE

- doc/over_sampling.rst
- doc/whats_new/v0.4.rst
- imblearn/over_sampling/_smote.py
> FIX: get the right index when tie breaking in SMOTE NC

- doc/under_sampling.rst
Sorry, it seems to me the definition is not completely correct.
> Edit Tomek Link definition

- doc/whats_new/v0.5.rst
- examples/plot_sampling_strategy_usage.py
- imblearn/over_sampling/base.py
- imblearn/under_sampling/base.py
Fixes #517 and #522 
I change the docstring about sampling strategy when it's a float as I mentioned in #517 and taking into consideration the changes proposed by snowparrot in the same issue.
> Fix docstring about sampling strategy for under and oversampling

- doc/api.rst
- doc/whats_new/v0.5.rst
> DOC: add borderline- and SVM-SMOTE to the API doc

- doc/whats_new/v0.5.rst
- imblearn/over_sampling/_smote.py
closes #535 
Fix issue of sparse format conversion in old scipy version.
> FIX: explicit conversion to original sparse format in SMOTENC

- doc/whats_new/v0.5.rst
- imblearn/combine/_smote_enn.py
- imblearn/combine/_smote_tomek.py
- imblearn/combine/tests/test_smote_enn.py
- imblearn/combine/tests/test_smote_tomek.py
Fixes #541 
This Merge Request adds n_jobs parameter for SMOTEENN and SMOTETomek
> [MRG+1] Parallelisation for SMOTEENN and SMOTETomek

- imblearn/base.py
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/under_sampling/_prototype_generation/_cluster_centroids.py
- imblearn/under_sampling/_prototype_selection/_condensed_nearest_neighbour.py
- imblearn/under_sampling/_prototype_selection/_edited_nearest_neighbours.py
- imblearn/under_sampling/_prototype_selection/_instance_hardness_threshold.py
- imblearn/under_sampling/_prototype_selection/_nearmiss.py
- imblearn/under_sampling/_prototype_selection/_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/_prototype_selection/_one_sided_selection.py
- imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
- imblearn/under_sampling/_prototype_selection/_tomek_links.py
- imblearn/utils/estimator_checks.py
Make use of the scikit-learn estimator tags to run our test suite.
> MAINT use sklearn estimator tag in our test suite

- doc/ensemble.rst
- doc/whats_new/v0.5.rst
- imblearn/ensemble/_weight_boosting.py
- imblearn/ensemble/tests/test_weight_boosting.py
I don't think that the referenced paper mentions something about stumps but this change keep us in line with the original implementation of `AdaBoostClassifier`
> [MRG] FIX use a stump as base estimator in RUSBoostClassifier

- doc/under_sampling.rst
The language in `under_sampling.rst` stated that the synthetic data set was not an _element of_ the real data set. More correctly put, the synthetic data is not a _subset of_ the real data.
> More precise set-theoretic language in `under_sampling` doc

- .travis.yml
- build_tools/travis/install.sh
- imblearn/utils/_show_versions.py
- imblearn/utils/tests/test_show_versions.py
- Drop `get_blas_info()` vendored from sklearn
- Fix unit tests to reflect the fix
`imblearn/utils/_show_versions` used several utilities from scikit-learn. BLAS/CBLAS were recently dropped and `get_blas_info()` was removed.
This patch reflects these changes.
See [scikit-learn#14205](https://github.com/scikit-learn/scikit-learn/pull/14205)
> [MRG] 👽 Maintenance for `imblearn.show_versions()`, fix Travis build

- imblearn/over_sampling/_smote.py
removing double string 'of' in runtime error
> remove double 'or' string in runtime error

- doc/conf.py
Some issue with documentation rendering solve in:
https://github.com/readthedocs/sphinx_rtd_theme/issues/766#issuecomment-517145293
> DOC fix spacing issue when using sphinx_rtd_theme

- doc/whats_new/v0.6.rst
- imblearn/pipeline.py
- imblearn/tests/test_pipeline.py
- setup.cfg
Synchronization of `imblearn.pipeline` with `sklearn.pipeline`.
> MNT synchronize imblearn.pipeline with sklearn.pipeline

- doc/whats_new/v0.6.rst
- imblearn/ensemble/_forest.py
- imblearn/ensemble/tests/test_forest.py
> MNT synchronize forest with scikit-learn

- setup.py
We should remove `keras` and `tensorflow` to be able to build the documentation on `readthedocs`.
We should find another solution later
> MNT remove keras and tensorflow from doc

- imblearn/metrics/_classification.py
Fix typo `fn` -> `fp`
Fix typo "false negatives" -> "false positives"
Fix removing empty reference: `_[1]` -> ` `
- Former issue on this topic: #592
- Fixes #613 
This fixes the wording in `imblearn.metrics._classification.specificity_score(...)`:
```diff
- ... `fn` the number of false negatives. ...
+ ... `fp` the number of false positives. ...
```
And drops an empty reference:
```diff
- ... false positives_[1].
+ ... false positives.
```
The latest [documentation for specificity score](https://imbalanced-learn.readthedocs.io/en/latest/generated/imblearn.metrics.specificity_score.html) does not seem to currently reflect the recent changes (e.g. #592).
It might be worth checking the sphinx builds on ReadTheDocs, *it's possible that they haven't been deploying recently*.
> Fix typos in specificity_score

- .travis.yml
- build_tools/travis/install.sh
- build_tools/travis/test_script.sh
- doc/datasets/index.rst
- doc/over_sampling.rst
- doc/under_sampling.rst
- doc/whats_new/v0.6.rst
- imblearn/datasets/_imbalance.py
- imblearn/datasets/tests/test_imbalance.py
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/over_sampling/tests/test_random_over_sampler.py
- imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
- imblearn/under_sampling/_prototype_selection/tests/test_random_under_sampler.py
`RandomUnderSampling`, RandomOverSampling`, `make_imbalance` accepts Pandas DataFrame in and will output Pandas DataFrame.
>  EHN RUS/ROS/make_imbalance accepts dataframe in/out

- doc/whats_new/v0.6.rst
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/over_sampling/tests/test_random_over_sampler.py
- imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
- imblearn/under_sampling/_prototype_selection/tests/test_random_under_sampler.py
closes #605 
Avoir rejecting array if they contain NaN or Inf in Random*Sampler. These samplers do not use the these information to sample therefore this is safe to propagate them.
> ENH accept non finite values in random samplers

- doc/whats_new/v0.6.rst
- imblearn/under_sampling/_prototype_selection/_edited_nearest_neighbours.py
- imblearn/under_sampling/_prototype_selection/tests/test_repeated_edited_nearest_neighbours.py
To mimic Scikit-Learn API of estimators that have a `max_iter` parameter, I have added `n_iter_` as an attribute after fitting. See [KMeans](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html) for such an example.
Fixed typo with my name in What's New v0.6
> [MRG] ENH: RepeatedENN `n_iter_` Attribute

- doc/whats_new/v0.6.rst
- imblearn/ensemble/_forest.py
- imblearn/ensemble/tests/test_forest.py
closes #655 
Resampling was not taken into account when computing the OOB score. Thus, the results was incorparting in-sample and leading to over-optimistic results.
> FIX incorporate resampling when computing OOB score in BRF

- CONTRIBUTING.md
Installing and calling pep8 as directed now leads to this warning
```
pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.
$ pip install pycodestyle
$ pycodestyle ...
```
This PR updates the contribution guide to reflect the name change.
> pep8 -> pycodestyle

- imblearn/base.py
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/over_sampling/_smote.py
- imblearn/under_sampling/_prototype_selection/_nearmiss.py
- imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
- imblearn/utils/_validation.py
- imblearn/utils/estimator_checks.py
- imblearn/utils/tests/test_validation.py
Follows #673. Fixes #666.
Adds better support for pandas and simple lists, if this is the case. 
Gradually we could support more array data types.
I created  new type for the job just to keep some state. 
~~The intention is to be private, thus no tested are provided.
Existing tests are passing, at least on my machine. Let's see what the CIs think.~~
> [MRG] Better in-out support

- .travis.yml
- README.rst
- azure-pipelines.yml
- build_tools/azure/install.sh
- build_tools/azure/posix-32.yml
- build_tools/travis/install.sh
- doc/install.rst
- setup.py
Fixing the CI since scikit-learn dropped support for python 3.5
> MNT/CI drop python 3.5

- doc/whats_new/v0.7.rst
- imblearn/ensemble/_forest.py
- imblearn/ensemble/tests/test_forest.py
The default value of `min_samples_leaf` in `BalancedRandomForestClassifier` constructor is 2, but in [doc](https://imbalanced-learn.readthedocs.io/en/stable/generated/imblearn.ensemble.BalancedRandomForestClassifier.html), the default value is 1.
This default value in `RandomForestClassifier`(sklearn) is also 1.
> fix: default parameter value inconsistent from doc

- azure-pipelines.yml
- doc/whats_new/v0.7.rst
- imblearn/pipeline.py
- imblearn/tests/test_pipeline.py
> Fix pipeline caching for older versions of joblib

- doc/whats_new/v0.7.rst
- imblearn/ensemble/_bagging.py
- imblearn/ensemble/_easy_ensemble.py
- imblearn/ensemble/_forest.py
- imblearn/ensemble/tests/test_forest.py
- imblearn/utils/_validation.py
- imblearn/utils/estimator_checks.py
closes #709 
Allow to pass the original `y` values without to encode the labels before hand.
> ENH accept string labels in classifier

- doc/whats_new/v0.7.rst
- imblearn/__init__.py
closes #704
Lazy import of keras when importing `imblearn`.
> ENH make lazy import of the keras module when importing imblearn

- doc/over_sampling.rst
- doc/whats_new/v0.7.rst
- imblearn/over_sampling/_smote.py
- imblearn/over_sampling/tests/test_smote_nc.py
closes #562 
Add a proper error message when only categorical features are provided to SMOTE-NC
> FIX raise proper error message when only categorical passed to SMOTE-NC

- doc/whats_new/v0.7.rst
- imblearn/base.py
- imblearn/combine/_smote_enn.py
- imblearn/combine/_smote_tomek.py
- imblearn/datasets/_imbalance.py
- imblearn/datasets/_zenodo.py
- imblearn/datasets/tests/test_imbalance.py
- imblearn/ensemble/_bagging.py
- imblearn/ensemble/_easy_ensemble.py
- imblearn/ensemble/_forest.py
- imblearn/ensemble/_weight_boosting.py
- imblearn/keras/_generator.py
- imblearn/metrics/_classification.py
- imblearn/over_sampling/_adasyn.py
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/over_sampling/_smote.py
- imblearn/tensorflow/_generator.py
- imblearn/under_sampling/_prototype_generation/_cluster_centroids.py
- imblearn/under_sampling/_prototype_selection/_condensed_nearest_neighbour.py
- imblearn/under_sampling/_prototype_selection/_edited_nearest_neighbours.py
- imblearn/under_sampling/_prototype_selection/_instance_hardness_threshold.py
- imblearn/under_sampling/_prototype_selection/_nearmiss.py
- imblearn/under_sampling/_prototype_selection/_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/_prototype_selection/_one_sided_selection.py
- imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
- imblearn/under_sampling/_prototype_selection/_tomek_links.py
- imblearn/under_sampling/_prototype_selection/tests/test_instance_hardness_threshold.py
- imblearn/utils/_validation.py
- imblearn/utils/tests/test_validation.py
closes #717 
Not allowing kwargs by position anymore. It is requiring a round of deprecation.
> MNT deprecate passing kwargs by position

- imblearn/metrics/tests/test_classification.py
- Drop `from sklearn.utils.fixes import np_version`
The specification for `np_version` changed in `scikit-learn`,
leading to an error when tests ran.
However, the test was whether the `numpy` version was less than
`1.7.0`, which is outside the minimum version specified in
`setup.py` and `requirements.txt`
Relevant PR in `scikit-learn`: https://github.com/scikit-learn/scikit-learn/pull/17670
> [MNT] 👽 Drop `np_version` import

- doc/whats_new/v0.7.rst
- imblearn/under_sampling/_prototype_generation/_cluster_centroids.py
- imblearn/under_sampling/_prototype_generation/tests/test_cluster_centroids.py
closes #741
closes #738 
When `voting="hard"` any sample from `X` could have been selected instead of a sample from `X[target_class]`.
> FIX select sample from the targeted class in ClusterCentroids

- doc/metrics.rst
- doc/whats_new/v0.7.rst
- imblearn/metrics/_classification.py
- imblearn/metrics/tests/test_classification.py
closes #758
Add `output_dict` to `classification_report_imbalanced`
> ENH add output_dict in classification_report_imbalanced

- examples/applications/porto_seguro_keras_under_sampling.py
- imblearn/keras/_generator.py
Remove the deprecation warning in keras
> MNT remove deprecation warning in keras example

- imblearn/pipeline.py
There is a small typo in imblearn/pipeline.py.
Should read `transformer` rather than `transfomer`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, transfomer -> transformer

- imblearn/base.py
I think while deprecating `fit_sample`, we forgot to remove the alias from the base class.
> MNT remove fit_sample alias from base class

- doc/api.rst
- doc/bibtex/refs.bib
- doc/metrics.rst
- doc/whats_new/v0.7.rst
- imblearn/metrics/__init__.py
- imblearn/metrics/_classification.py
- imblearn/metrics/tests/test_classification.py
As detailed in the [issue #18901](https://github.com/scikit-learn/scikit-learn/issues/18901) I wrote in Scikit-Learn main repository, Macro-Averaged MAE should be added to **imbalanced-learn** repository instead.  
For **ordinal classification**, we can use multiple metrics, for example: MAE, MSE... As we would use for regression.
But when these classes are imbalanced, one way to deal with imbalance is to use macro-averaged MAE instead, as described on [StackExchange](https://stats.stackexchange.com/questions/338904/measures-of-ordinal-classification-error-for-ordinal-regression) and in the [original paper](https://www.computer.org/csdl/proceedings-article/2009/isda/3872a283/12OmNybfrbj).
The macro-averaged MAE is like the "classic" MAE, except we compute each MAE for each class  and …
> FEA Add macro-averaged mean absolute error

- doc/whats_new/v0.7.rst
- imblearn/base.py
- imblearn/tests/test_base.py
closes #782 
Make sure that input validations are bypass if `validate=False` even when only `fit` is called.
> FIX make sure that FunctionSampler will bypass validation in fit

- doc/over_sampling.rst
- doc/whats_new/v0.7.rst
- examples/over-sampling/plot_comparison_over_sampling.py
- examples/over-sampling/plot_shrinkage_effect.py
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/over_sampling/tests/test_random_over_sampler.py
closes #792
Remove the `smoothed_bootstrap` param and only keep `shrinkage` to control the bootstrapping.
> FIX remove smoothed_bootstrap and use only shrinkage param

- doc/datasets/index.rst
- doc/miscellaneous.rst
- examples/datasets/plot_make_imbalance.py
> DOC use tilde in mod func class

- .flake8
- doc/api.rst
- doc/bibtex/refs.bib
- doc/conf.py
- doc/metrics.rst
- doc/whats_new/v0.7.rst
- imblearn/metrics/_classification.py
- imblearn/metrics/pairwise.py
- imblearn/metrics/tests/test_pairwise.py
- references.bib
> FEA add ValueDifferenceMetric as a pairwise metric

- imblearn/base.py
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
- imblearn/utils/estimator_checks.py
closes #650 
Add tags "sparse" and "dataframe" as two tags that could be added to `X_types`.
> TST create sparse and dataframe tags for X_types

- imblearn/over_sampling/_smote.py
Use string substitution in docstring of `SMOTENC`
> DOC fix the documentation to use substitution

- README.rst
- doc/over_sampling.rst
- doc/references/over_sampling.rst
- doc/whats_new/v0.8.rst
- imblearn/over_sampling/__init__.py
- imblearn/over_sampling/_adasyn.py
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/over_sampling/_smote.py
- imblearn/over_sampling/tests/test_smoten.py
closes #565 
Implements SMOTE for nominal categorical features only. It uses the VDM distance and a majority vote regarding the per feature to create new categories from the k-NN.
> FEA implements SMOTEN to handle nominal categorical features

- build_tools/circle/build_doc.sh
- doc/conf.py
- examples/api/plot_sampling_strategy_usage.py
- examples/applications/plot_impact_imbalanced_classes.py
- examples/applications/plot_multi_class_under_sampling.py
- examples/ensemble/plot_comparison_ensemble_classifier.py
- requirements.doc.txt
- setup.py
Improve the example style with newer marker.
> DOC improve examples styles

- doc/whats_new/v0.8.rst
- imblearn/utils/testing.py
- imblearn/utils/tests/test_testing.py
closes #807
Deprecate `imblearn.utils.testing.warns` context manager.
> DEP deprecate warns context manager

- doc/whats_new/v0.8.rst
- requirements.dev.txt
- requirements.doc.txt
- requirements.optional.txt
- requirements.test.txt
- requirements.txt
- setup.py
closes #810 
Remove the `requirements` file in favour of `extras_require` in `setup.py`.
> MNT remove requirements files and move it in setup.py

- examples/over-sampling/plot_shrinkage_effect.py
Solves #821 
Fixes the cropped axis name by adding plt.tight_layout() exlicitly
> DOC avoid clipping axis name in example

- imblearn/over_sampling/_smote/base.py
> DOC fix a typo in imblearn/over_sampling/_smote/base.py (#832)

- README.rst
Fixes #839
The minimum version for scikit-learn was outdated; the change was introduced in this commit https://github.com/scikit-learn-contrib/imbalanced-learn/commit/f40e654c20c9c6ec4d77904278f0560997347fa9 but the README.rst was never updated.
> [MRG] Update sklearn minimum version

- build_tools/azure/posix.yml
Caching the dataset between jobs.
> CI cache data directory

- doc/under_sampling.rst
close #862 
`\in` changed to `\subset` in `doc/under_sampling.rst` protype section.
P.n: I'm not sure which branch should I PR to but I think `master` is the best choice
> DOC use proper math symbol for subset

- doc/ensemble.rst
A minor misspelling in the documentation
> DOC typo in user guide

- doc/whats_new/v0.10.rst
- imblearn/over_sampling/_adasyn.py
- imblearn/over_sampling/_smote/base.py
- imblearn/over_sampling/_smote/filter.py
- imblearn/over_sampling/tests/test_common.py
Most of the time `n_jobs` is not used anymore. Currently it was really useful to use it in scikit-learn and it can be set directly by passing an estimator with the parameter set which is a better choice.
> MAINT deprecate n_jobs in over-sampling algorithms

- doc/developers_utils.rst
- imblearn/metrics/tests/test_classification.py
- imblearn/under_sampling/_prototype_generation/_cluster_centroids.py
- imblearn/under_sampling/_prototype_generation/tests/test_cluster_centroids.py
- imblearn/utils/deprecation.py
- imblearn/utils/testing.py
- imblearn/utils/tests/test_deprecation.py
- imblearn/utils/tests/test_testing.py
- imblearn/utils/tests/test_validation.py
Remove functions that have been deprecated for 2 versions.
> MAINT remove deprecated function

- imblearn/under_sampling/_prototype_selection/_instance_hardness_threshold.py
closes #889 
Fix removing the information that one can pass some string. This is not supported since 5 years ago.
> DOC fix estimator documentation in IHT

- conftest.py
The CI is failing because our documentation expects to use `keras` embedded in `tensorflow`.
Our doctest skipping is expecting to use directly keras.
> MAINT using keras from tensorflow to skip doctest

- README.rst
In README.rst it mentions that there are two techniques instead of four.
> Update README.rst to correct the number of re-sampling techniques

- imblearn/over_sampling/_smote/base.py
N/A
Value error in `_validate_estimator` method of `SMOTENC` class does not account for zero-based indexing. Subtracting 1 from n_features takes care of this.
> update error message to account for zero based indexing

- doc/miscellaneous.rst
> DOC fix some typo in miscellaneous.rst

- doc/whats_new/v0.10.rst
- imblearn/utils/_docstring.py
- imblearn/utils/tests/test_docstring.py
closes #945 
Make sure we can execute code with `python -OO`.
It implies that the docstring ingestion should not fail.
> FIX make sure we can execute code with python -OO

- imblearn/pipeline.py
closes #904 
add information regarding the quirk of imbalanced-learn pipelines where `fit_transform` is different from `fit.transform`.
> DOC add a warning regarding fit_transform != fit.transform

- imblearn/utils/_param_validation.py
- imblearn/utils/tests/test_param_validation.py
Add support for dataframe in parameter validation framework.
> MAINT add support for dataframe in parameter validation framework

- doc/whats_new/v0.10.rst
- imblearn/base.py
- imblearn/combine/_smote_enn.py
- imblearn/combine/_smote_tomek.py
- imblearn/metrics/pairwise.py
- imblearn/over_sampling/_adasyn.py
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/over_sampling/_smote/base.py
- imblearn/over_sampling/_smote/cluster.py
- imblearn/over_sampling/_smote/filter.py
- imblearn/tests/test_common.py
- imblearn/under_sampling/_prototype_generation/_cluster_centroids.py
- imblearn/under_sampling/_prototype_selection/_condensed_nearest_neighbour.py
- imblearn/under_sampling/_prototype_selection/_edited_nearest_neighbours.py
- imblearn/under_sampling/_prototype_selection/_instance_hardness_threshold.py
- imblearn/under_sampling/_prototype_selection/_nearmiss.py
- imblearn/under_sampling/_prototype_selection/_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/_prototype_selection/_one_sided_selection.py
- imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
- imblearn/under_sampling/_prototype_selection/_tomek_links.py
- imblearn/utils/estimator_checks.py
Add support for:
- `feature_names_in_`
- `get_feature_names_out`
> MAINT add support for feature_names_in_

- azure-pipelines.yml
- imblearn/ensemble/tests/test_bagging.py
- imblearn/keras/tests/test_generator.py
- imblearn/tests/test_pipeline.py
Adding a build for scikit-learn 1.1 since 1.2 is the latest release now.
> MAINT create a new build for intermediate scikit-learn

- doc/whats_new/v0.10.rst
- imblearn/over_sampling/base.py
- imblearn/over_sampling/tests/test_random_over_sampler.py
- imblearn/under_sampling/_prototype_selection/tests/test_random_under_sampler.py
- imblearn/under_sampling/_prototype_selection/tests/test_tomek_links.py
while using smapling strategy ="minority" we were getting error. i found issue in base.py of oversampler where in _parameter constraint majority was used in stroptions instead of minority
> FIX make sure to accept "minority" as a valid strategy in over-samplers

- azure-pipelines.yml
Trying to fix the CIs for minimum tensorflow and keras.
> MAINT pin numpy and scipy version for minimum keras/tensorflow

- doc/whats_new/v0.11.rst
- imblearn/over_sampling/_smote/base.py
- imblearn/over_sampling/_smote/tests/test_smote_nc.py
closes #990 
Add a `categorical_encoder` parameter to `SMOTENC` in order to customize the parameters of the encoder easily.
> ENH add categorical_encoder param to SMOTENC

- doc/whats_new/v0.11.rst
- imblearn/over_sampling/_smote/base.py
- imblearn/over_sampling/_smote/tests/test_smote_nc.py
closes #974 
We previously validated the entire input data and try to convert all features to numerical values. Now, we first split the input data into two sets and only convert to numerical, the continuous feature and keep the data as-is and delegate the conversion to the scikit-learn encoder.
> FIX handle heterogeneous data type in categorical feature in SMOTENC

- doc/whats_new/v0.11.rst
- imblearn/over_sampling/_smote/base.py
- imblearn/over_sampling/_smote/tests/test_smoten.py
Add a new parameter `categorical_encoder` to `SMOTEN`.
Additionally, there is a new `categorical_encoder_` as a fitted attribute.
> ENH add categorical_encoder to SMOTEN

- README.rst
Originally the badges look like this:
As you can see, the CircleCI badge is broken. It doesn't seem that `token` is needed for the badge. This is similar to https://github.com/scikit-learn/scikit-learn/pull/26183
> Fixed CircleCI badge in README

- doc/whats_new/v0.11.rst
- imblearn/over_sampling/_smote/base.py
- imblearn/over_sampling/_smote/tests/test_smoten.py
closes #971 
Handle sparse matrices at the cost of efficiency in `SMOTEN`.
> FIX handle sparse matrices in SMOTEN

- build_tools/circle/build_doc.sh
- doc/conf.py
- imblearn/_min_dependencies.py
Improve the UX of the documentation by using `sphinx-copybutton`.
> MAINT use sphinx-copybutton extension

- doc/whats_new/v0.11.rst
- examples/api/plot_sampling_strategy_usage.py
- imblearn/datasets/tests/test_imbalance.py
- imblearn/ensemble/tests/test_bagging.py
- imblearn/over_sampling/_random_over_sampler.py
- imblearn/over_sampling/_smote/base.py
- imblearn/over_sampling/tests/test_random_over_sampler.py
- imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
- imblearn/under_sampling/_prototype_selection/tests/test_random_under_sampler.py
- imblearn/utils/_validation.py
- imblearn/utils/fixes.py
closes #970
Do not convert input data in `RandomUnderSampler` and `RandomOverSampler` since the basic strategy will only get original rows.
> ENH allow any dtype in input from RandomSampler

- doc/ensemble.rst
- doc/whats_new/v0.11.rst
- examples/applications/plot_impact_imbalanced_classes.py
- examples/ensemble/plot_comparison_ensemble_classifier.py
- imblearn/ensemble/_forest.py
- imblearn/ensemble/tests/test_forest.py
- imblearn/utils/estimator_checks.py
closes #838 
Change the default of `replacement` and `sampling_strategy` in `BalancedRandomForestClassifier`. We use a deprecation cycle since the impact might not be enough to consider it as a bug and break the backwards compatibility.
> API change default of replacement and sampling_strategy in BRF

- examples/applications/porto_seguro_keras_under_sampling.py
N/A
This pull request fixes an AttributeError in the Sequential object when using the `predict_proba` method. The Sequential class in TensorFlow does not have a `predict_proba` method. Instead, it has been deprecated in favour of the `predict` method, which directly returns the predicted class probabilities.
N/A
> [MRG] Fix AttributeError in Sequential object - predict_proba

- doc/whats_new/v0.11.rst
- imblearn/utils/_validation.py
- imblearn/utils/tests/test_validation.py
closes #979 
Remove spurious warning that is raised when many samples are created in the minority class such that it is larger than the number of sample available in the majority class.
> FIX remove spurious warning raised when over-sampling the minority class

- doc/over_sampling.rst
- doc/whats_new/v0.11.rst
- imblearn/over_sampling/_smote/base.py
- imblearn/over_sampling/_smote/tests/test_smote_nc.py
Make it possible to pass an array-like of `str` as a parameter of `categorical_features` for `SMOTENC`.
> ENH support array-like of str for categorical_features in SMOTENC

- doc/over_sampling.rst
- doc/whats_new/v0.11.rst
- imblearn/over_sampling/_smote/base.py
- imblearn/over_sampling/_smote/tests/test_smote_nc.py
Add the option `categorical_features="auto"` that detects categorical features if they are using `pd.CategoricalDtype` in `SMOTENC` estimator.
In addition, we need to make sure that we don't only have numerical features after the inference, in which case, we raise an error.
> ENH add auto inference based on pd.CategoricalDtype in SMOTENC

- doc/whats_new/v0.11.rst
- imblearn/metrics/_classification.py
- imblearn/metrics/tests/test_classification.py
Fixes https://github.com/scikit-learn-contrib/imbalanced-learn/issues/863
When `output_dict=True` and `target_names` is given, set the keys of the `output_dict` to the corresponding `target_names`
```
{'label 1': {'pre':0.5,
'rec':1.0,
...
},
'label 2': { ... },
...
}
```
When `output_dict=True` and `target_names` is not given, set the keys of the `output_dict` to the corresponding labels in `str` format
```
{'0': {'pre':0.5,
'rec':1.0,
...
},
'1': { ... },
...
}
```
> FIX do not ignore `target_names` when `output_dict=True` in `classification_report_imbalanced`

- imblearn/utils/estimator_checks.py
Fixes #672 
- Created a common fixture to create a sample dataset used in tests.
- Replaced boilerplate code with fixture in necessary tests in `estimator_checks.py`.
> MAINT Add fixture for dataset generation in common tests

- doc/ensemble.rst
- doc/whats_new/v0.11.rst
- examples/applications/plot_impact_imbalanced_classes.py
- examples/ensemble/plot_comparison_ensemble_classifier.py
- imblearn/ensemble/_forest.py
- imblearn/ensemble/tests/test_forest.py
- imblearn/tests/test_docstring_parameters.py
- imblearn/utils/estimator_checks.py
closes #838 
To avoid 2 bootstraps, we also need to change the default of `bootstrap`.
> API change behaviour of bootstrap in BRF

- doc/whats_new/v0.12.rst
- imblearn/under_sampling/_prototype_selection/_condensed_nearest_neighbour.py
- imblearn/under_sampling/_prototype_selection/_one_sided_selection.py
- imblearn/under_sampling/_prototype_selection/tests/test_condensed_nearest_neighbour.py
- imblearn/under_sampling/_prototype_selection/tests/test_one_sided_selection.py
closes #908 
We should make sure that the documentation mentions the one-vs.-other strategy (wrong for CNN). Then it makes sense to store all pairs of k-NN instead of the last one from the loop.
We can then deprecate `estimator_` and create a new `estimators_` attribute.
> API deprecate estimator_ in favor of estimators_ in CNN and OSS

- doc/under_sampling.rst
- doc/whats_new/v0.12.rst
- examples/under-sampling/plot_comparison_under_sampling.py
- imblearn/under_sampling/_prototype_selection/_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/_prototype_selection/tests/test_neighbourhood_cleaning_rule.py
closes #764 
Solve several issues in `NeighbourhoodCleaningRule`:
- apply the `threshold_cleaning` on the minority classes and not the full dataset
- deprecate `kind_sel` since it does not make in regards to the proposed literature. We need to remove samples that are linked with the misclassification of samples using the NN rule for the minority class.
- Make the code for this selection clearer.
> FIX/DEPR follow literature for the implementation of NCR

- imblearn/under_sampling/_prototype_selection/_instance_hardness_threshold.py
closes #848 
Update the docstring regarding the multiclass approach used in IHT. We don't use one vs. rest. Instead, we filter samples based on their classes and the assigned probabilities of a learner.
> DOC fix the strategy used for multiclass in IHT

- doc/over_sampling.rst
- doc/whats_new/v0.11.rst
- imblearn/over_sampling/_smote/base.py
closes #857 
Since euclidean distance is used, we should divide by `sqrt(2)` instead of `2`.
> FIX divide by sqrt(2) the median entry in SMOTENC

- doc/whats_new/v0.11.rst
- imblearn/over_sampling/_smote/filter.py
- imblearn/over_sampling/_smote/tests/test_svm_smote.py
closes #742 
In the case that all support vectors are detected as noise in `SVMSMOTE`, there is no other choice than raise a proper error.
> FIX raise informative error message when SV are all noise

- doc/whats_new/v0.11.rst
- imblearn/over_sampling/_smote/filter.py
- imblearn/over_sampling/_smote/tests/test_borderline_smote.py
closes #846 
Make sure that we use the full dataset to generate new samples in `BorderlineSMOTE` version 2.
> FIX BorddelineSMOTE-2 use the full dataset to generate new sample

- doc/install.rst
closes #991 
Add information about scikit-learn-intelex in the installation guideline.
> DOC add section about scikit-learn-intelex

- doc/under_sampling.rst
related to #853
separating in smaller PRs as requested.
Final one ;)
> DOC improve the documentation of CNN and OSS

- imblearn/under_sampling/_prototype_selection/_edited_nearest_neighbours.py
related to https://github.com/scikit-learn-contrib/imbalanced-learn/pull/850
separating in smaller PRs as requested.
Here I modify all docstrings, but since parameters are the same, you'll see that is the same changes in each class.
> DOC improve documentation for ENN and variants

- doc/under_sampling.rst
related to #853 
Creating smaller PRs as requested
> DOC improve documentation of RandomUnderSampler

- doc/under_sampling.rst
related to #853 
Creating smaller PRs as per request.
> DOC improve TomekLinks documentation

- doc/under_sampling.rst
related to #850 
separating in smaller PRs as requested.
> DOC improve ENN documentation

- doc/under_sampling.rst
related to #853
As per request, splitting into smaller PRs
> DOC improve introduction to undersampling methods

- doc/under_sampling.rst
- imblearn/under_sampling/_prototype_selection/_instance_hardness_threshold.py
relates to #853 
making smaller PRs as requested
> DOC improve instance hardness threshold user guide

- doc/developers_utils.rst
- imblearn/under_sampling/_prototype_selection/_condensed_nearest_neighbour.py
Fixes #1040.
This is a suggestion to use the same dataset generator `sklearn.datasets.make_classification` as is used in the doc of e.g. `ClusterCentroids` instead of the dead `sklearn.datasets.fetch_mldata`.
This is a suggestion, if you are interested in a low-cost fix. There may be more interesting datasets which could be used, or ones you find more illustrative.
btw pycodestyle gave me a few warnings of E501 about lines being longer than 79 characters, but I think you have a max line length of 88 in your checks which I think is also fine.
> DOC udpate the datasets used in CondensedNearestNeighbour docstring

- azure-pipelines.yml
- doc/ensemble.rst
- doc/whats_new/v0.12.rst
- imblearn/ensemble/_bagging.py
- imblearn/ensemble/_easy_ensemble.py
- imblearn/ensemble/_forest.py
- imblearn/ensemble/_weight_boosting.py
- imblearn/ensemble/tests/test_bagging.py
- imblearn/ensemble/tests/test_easy_ensemble.py
- imblearn/ensemble/tests/test_forest.py
- imblearn/ensemble/tests/test_weight_boosting.py
- imblearn/over_sampling/_smote/tests/test_smoten.py
- imblearn/tests/test_base.py
- imblearn/tests/test_common.py
- imblearn/tests/test_docstring_parameters.py
- imblearn/utils/_param_validation.py
- imblearn/utils/tests/test_estimator_checks.py
- imblearn/utils/tests/test_param_validation.py
Some compatibility fixes for scikit-learn 1.4
> MAINT compatibility sklearn 1.4

- examples/applications/porto_seguro_keras_under_sampling.py
- imblearn/_config.py
- imblearn/base.py
- imblearn/ensemble/_bagging.py
- imblearn/ensemble/_easy_ensemble.py
- imblearn/ensemble/_forest.py
- imblearn/ensemble/_weight_boosting.py
- imblearn/keras/tests/test_generator.py
- imblearn/tests/test_pipeline.py
- imblearn/utils/_available_if.py
closes #1062
Fix a couple of tests and import due to the release of scikit-learn 1.4.1.post1
> MAINT update tests and import for sklearn 1.4.1

- doc/whats_new/v0.12.rst
- imblearn/under_sampling/_prototype_selection/_instance_hardness_threshold.py
- imblearn/under_sampling/_prototype_selection/tests/test_instance_hardness_threshold.py
Added the option to add a pipeline as an estimator for instance hardness threshold. Currently using a pipeline as an estimator fails because of the instance check. I think it's useful to be able to use pipelines as estimators and have thus added it.
> FIX InstanceHardnessThreshold accepts classifier included in a Pipeline

- doc/whats_new/v0.12.rst
- imblearn/_min_dependencies.py
- imblearn/tensorflow/tests/test_generator.py
Distutils is deprecated. Use the equivalent function from the [`packaging` package](https://pypi.org/project/packaging/) instead. Pytest and others already depend on that, but I added it to the test dependencies to be sure.
This patch was [needed in the Debian package of `imbalanced-learn`.](https://salsa.debian.org/med-team/imbalanced-learn/-/blob/master/debian/patches/python-3.12.patch?ref_type=heads)
> MAINT drop disutils and use scikit-learn fixes instead

- doc/whats_new/v0.12.rst
- imblearn/utils/tests/test_docstring.py
- setup.py
closes #1071
Update the supported python version and anticipate the release of Python 3.13.
> MAINT update the python version supported

- doc/whats_new/v0.12.rst
- imblearn/utils/tests/test_docstring.py
Made a mistake in the original fix.
> FIX change the way we check for a specific Python version in the test suite

- doc/whats_new/0.13.rst
- imblearn/ensemble/_bagging.py
- imblearn/ensemble/_easy_ensemble.py
- imblearn/over_sampling/_smote/base.py
- imblearn/pipeline.py
- imblearn/utils/_metadata_requests.py
Preparing the future release and the compatibility with scikit-learn 1.5
> MAINT compatibility sklearn 1.5

- azure-pipelines.yml
- conftest.py
- imblearn/metrics/pairwise.py
- imblearn/utils/estimator_checks.py
This PR makes sure that we are compatible with scikit-learn 1.5.2 and NumPy >2
> MAINT compatibility scikit-learn 1.5.2 and Numpy 2

- imblearn/combine/_smote_enn.py
- imblearn/combine/_smote_tomek.py
- imblearn/combine/tests/test_smote_enn.py
- imblearn/combine/tests/test_smote_tomek.py
- imblearn/ensemble/_bagging.py
- imblearn/ensemble/_easy_ensemble.py
- imblearn/ensemble/_forest.py
- imblearn/ensemble/tests/test_forest.py
- imblearn/over_sampling/_adasyn.py
- imblearn/over_sampling/_smote/base.py
- imblearn/over_sampling/_smote/cluster.py
- imblearn/over_sampling/_smote/filter.py
- imblearn/over_sampling/_smote/tests/test_smote_nc.py
- imblearn/over_sampling/tests/test_common.py
- imblearn/over_sampling/tests/test_random_over_sampler.py
- imblearn/pipeline.py
- imblearn/under_sampling/_prototype_selection/tests/test_random_under_sampler.py
- imblearn/utils/estimator_checks.py
- pixi.lock
Remove deprecated parameters and address other TODO for `imbalanced-learn` 0.13 release.
> MAINT remove deprecated params for 0.13

- doc/introduction.rst
N/A
This PR reworks the [introduction section of the user guide](https://imbalanced-learn.org/stable/introduction.html) to improve its organisation and logical flow.
Here is a preview:
N/A
> DOC rework the introduction section of the user guide

- imblearn/base.py
- imblearn/pipeline.py
Let's use public module for metadata routing and let's monkey patch the methods supported next to our base class where `fit_resample` is declared.
> MAINT use public import for metadata routing

- imblearn/base.py
- imblearn/pipeline.py
- imblearn/tests/test_pipeline.py
closes #1111 
This PR fixes a bug in `Pipeline` that properly defines how metadata should be routed with a sampler.
> FIX forward properly the metadata with the pipeline

- doc/ensemble.rst
Many English errors in this doc, fixed most.
None.
Many errors in the English of this documentation.
> Fixed grammar

- imblearn/ensemble/_easy_ensemble.py
- imblearn/metrics/tests/test_classification.py
- imblearn/over_sampling/_smote/base.py
- imblearn/tests/test_pipeline.py
closes #1131
Fixing a couple of small issue mainly.
It should also fix the issue observed in #1131
> MAINT fix compatibility with scikit-learn 1.7

- README.rst
- doc/install.rst
- doc/whats_new/0.14.rst
- examples/model_selection/plot_instance_hardness_cv.py
- imblearn/ensemble/_bagging.py
- imblearn/ensemble/_common.py
- imblearn/ensemble/_easy_ensemble.py
- imblearn/ensemble/_forest.py
- imblearn/keras/_generator.py
- imblearn/under_sampling/_prototype_selection/_condensed_nearest_neighbour.py
- imblearn/under_sampling/_prototype_selection/_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/_prototype_selection/_one_sided_selection.py
- imblearn/under_sampling/_prototype_selection/tests/test_condensed_nearest_neighbour.py
- imblearn/under_sampling/_prototype_selection/tests/test_neighbourhood_cleaning_rule.py
- imblearn/under_sampling/_prototype_selection/tests/test_one_sided_selection.py
- pixi.lock
- pyproject.toml
Preparing the upcoming 0.14 release
> MAINT prepare release 0.14
