UnbalancedDataset.py

The global functions is_tomek, make_samples, in_danger and
is_noise, are now static methods. I believe it makes more sense
this way.

This commit changes all global function to static methods.

---

setup.py
unbalanced_dataset/pipeline.py

Adds a setup.py script. Tested by cloning the branch and installing it in a clean virtualenv and it worked.

Introducing setup.py

---

unbalanced_dataset/over_sampling/smote.py

- Update the documentation of `make_samples`
- Make the function `in_danger_noise` and `make_samples` private

[MRG] Address issue #52

---

unbalanced_dataset/pipeline.py

Docstring fix in `sample` method

Doc fix in pipeline

---

.gitignore

I'm using visual studio. So, it would be nice if the files of the visual studio projects were ignored.

Add visual studio project files in .gitignore

---

imblearn/datasets/tests/test_make_imbalance.py

[MRG] Adress issue #133 - Change assert by assert_true

---

doc/whats_new.rst
imblearn/under_sampling/edited_nearest_neighbours.py
imblearn/under_sampling/tests/test_repeated_edited_nearest_neighbours.py

@dvro @chkoar If you could check into details the two criteria that I added.

[MRG] Address issue #129 - Add specific stopping criteria for the RENN

---

CONTRIBUTING.md
examples/plot_unbalanced_dataset.ipynb

Fix the directory in the CONTRIBUTING file and an example description.
Ref #127

Remove last UnbalancedDataset references

---

imblearn/pipeline.py
imblearn/tests/test_pipeline.py

Adress #176 - Fix "fit then sample" bug in pipeline

---

imblearn/base.py
imblearn/combine/smote_enn.py
imblearn/combine/smote_tomek.py
imblearn/ensemble/balance_cascade.py
imblearn/ensemble/easy_ensemble.py
imblearn/over_sampling/adasyn.py
imblearn/over_sampling/random_over_sampler.py
imblearn/over_sampling/smote.py
imblearn/under_sampling/cluster_centroids.py
imblearn/under_sampling/condensed_nearest_neighbour.py
imblearn/under_sampling/edited_nearest_neighbours.py
imblearn/under_sampling/instance_hardness_threshold.py
imblearn/under_sampling/nearmiss.py
imblearn/under_sampling/neighbourhood_cleaning_rule.py
imblearn/under_sampling/one_sided_selection.py
imblearn/under_sampling/random_under_sampler.py
imblearn/under_sampling/tomek_links.py

This is the PR linked to issue #175

[MRG+1] Address issue #175

---

imblearn/combine/smote_enn.py
imblearn/combine/smote_tomek.py
imblearn/combine/tests/test_smote_enn.py
imblearn/combine/tests/test_smote_tomek.py

Start resampling the combine methods as stated in issue #174

[MRG+1] Refactor combine methods

---

imblearn/combine/smote_enn.py
imblearn/combine/smote_tomek.py
imblearn/over_sampling/smote.py
imblearn/pipeline.py
imblearn/under_sampling/cluster_centroids.py
imblearn/under_sampling/condensed_nearest_neighbour.py
imblearn/under_sampling/edited_nearest_neighbours.py
imblearn/under_sampling/instance_hardness_threshold.py
imblearn/under_sampling/nearmiss.py
imblearn/under_sampling/neighbourhood_cleaning_rule.py
imblearn/under_sampling/one_sided_selection.py
imblearn/under_sampling/random_under_sampler.py
imblearn/under_sampling/tests/test_condensed_nearest_neighbour.py
imblearn/under_sampling/tests/test_edited_nearest_neighbours.py
imblearn/under_sampling/tests/test_neighbourhood_cleaning_rule.py
imblearn/under_sampling/tests/test_one_sided_selection.py
imblearn/under_sampling/tests/test_tomek_links.py
imblearn/under_sampling/tomek_links.py

Push the number of jobs `n_jobs=1` by default

[MRG] Make n_jobs default to 1

---

.travis.yml
Makefile
build_tools/travis/flake8_diff.sh
build_tools/travis/install.sh
build_tools/travis/test_script.sh
imblearn/combine/smote_enn.py

Issue #205 
Make a travis check for `flake8`

[WIP] ENH flake8

---

examples/model_selection/plot_validation_curve.py

Adds an example visualizing the impact of the `SMOTE`'s `k_neighbors` parameter.

[MRG] Add an example using validation curves

---

imblearn/base.py
imblearn/under_sampling/instance_hardness_threshold.py

Use the `sklearn` externals module instead of `six` directly.

[MRG] ENH Remove six dependency

---

imblearn/metrics/classification.py
imblearn/metrics/tests/test_classification.py

FIX IBA metrics

---

README.rst

FIX Update the README

---

imblearn/base.py

[MRG] FIX create a real mixin

---

setup.py

Removes an unused variable from `setup.py`

Remove unused variable

---

conda-recipe/conda_deployement.sh

[MRG] MAINT add script for automatic upload in anaconda cloud

---

doc/conf.py

[MRG] DOC/FIX fix sklearn clickable links

---

examples/applications/plot_over_sampling_benchmark_lfw.py
examples/under-sampling/plot_tomek_links.py

[MRG] DOC/EXA solve Tomek examples

---

imblearn/under_sampling/cluster_centroids.py

DOC remove the term experimental

---

imblearn/over_sampling/smote.py

[MRG] DOC mention which parameters is associated to which version of SMOTE

---

imblearn/base.py
imblearn/combine/smote_enn.py
imblearn/combine/smote_tomek.py
imblearn/datasets/imbalance.py
imblearn/datasets/tests/test_make_imbalance.py
imblearn/ensemble/balance_cascade.py
imblearn/ensemble/easy_ensemble.py
imblearn/exceptions.py
imblearn/metrics/classification.py
imblearn/over_sampling/adasyn.py
imblearn/over_sampling/random_over_sampler.py
imblearn/over_sampling/smote.py
imblearn/pipeline.py
imblearn/under_sampling/cluster_centroids.py
imblearn/under_sampling/condensed_nearest_neighbour.py
imblearn/under_sampling/edited_nearest_neighbours.py
imblearn/under_sampling/instance_hardness_threshold.py
imblearn/under_sampling/nearmiss.py
imblearn/under_sampling/neighbourhood_cleaning_rule.py
imblearn/under_sampling/one_sided_selection.py
imblearn/under_sampling/random_under_sampler.py
imblearn/under_sampling/tomek_links.py
imblearn/utils/estimator_checks.py
imblearn/utils/testing.py
imblearn/utils/validation.py

Fixes #248
Add authorships of the different methods

[MRG] DOC add authorship for later recalling

---

imblearn/setup.py
setup.py

[MRG] FIX fix setup

---

imblearn/under_sampling/prototype_selection/random_under_sampler.py

[MRG] FIX/DOC add replacement parameter in the docstring of RUS

---

.travis.yml
README.rst
appveyor.yml
build_tools/travis/install.sh
circle.yml
imblearn/combine/tests/test_smote_enn.py
imblearn/combine/tests/test_smote_tomek.py
imblearn/datasets/tests/test_make_imbalance.py
imblearn/datasets/tests/test_zenodo.py
imblearn/ensemble/tests/test_balance_cascade.py
imblearn/ensemble/tests/test_easy_ensemble.py
imblearn/metrics/classification.py
imblearn/metrics/tests/test_classification.py
imblearn/metrics/tests/test_score_objects.py
imblearn/over_sampling/tests/test_adasyn.py
imblearn/over_sampling/tests/test_random_over_sampler.py
imblearn/over_sampling/tests/test_smote.py
imblearn/under_sampling/prototype_generation/tests/test_cluster_centroids.py
imblearn/under_sampling/prototype_selection/tests/test_allknn.py
imblearn/under_sampling/prototype_selection/tests/test_condensed_nearest_neighbour.py
imblearn/under_sampling/prototype_selection/tests/test_edited_nearest_neighbours.py
imblearn/under_sampling/prototype_selection/tests/test_instance_hardness_threshold.py
imblearn/under_sampling/prototype_selection/tests/test_neighbourhood_cleaning_rule.py
imblearn/under_sampling/prototype_selection/tests/test_one_sided_selection.py
imblearn/under_sampling/prototype_selection/tests/test_random_under_sampler.py
imblearn/under_sampling/prototype_selection/tests/test_repeated_edited_nearest_neighbours.py
imblearn/under_sampling/prototype_selection/tests/test_tomek_links.py
imblearn/version.py
requirements.txt
setup.py

closes #305 
closes #302
add more platforms to be tested.

[MRG] Add more platform for testing

---

build_tools/travis/install.sh
conda-recipe/README.md
conda-recipe/conda_deployement.sh
conda-recipe/imbalanced-learn/meta.yaml

[WIP] CI update conda build and check doc

---

imblearn/base.py

[MRG] FIX remove sampling_type

---

build_tools/circle/build_doc.sh

MAINT downgrade sphinx-gallery to 0.1.11 for the moment

---

README.rst

Update badges such that they are always synchonized with the setup.py and pypi

MAINT Update README

---

build_tools/circle/build_doc.sh
doc/conf.py

MAINT switch back to sphinx 0.1.12

---

conda-recipe/imbalanced-learn/meta.yaml

BUILD remove unecessary package and build noarch

---

build_tools/circle/build_doc.sh
conda-recipe/imbalanced-learn/meta.yaml
doc/combine.rst
doc/conf.py
doc/developers_utils.rst
imblearn/under_sampling/prototype_selection/neighbourhood_cleaning_rule.py
imblearn/version.py
setup.cfg

Release 0.3.1

---

doc/over_sampling.rst

[MRG] DOC fix borderline-1 explanations

---

.travis.yml
imblearn/_version.py

CI allow_failures when testing on scikit-learn master

---

doc/introduction.rst

In 
> -and adding a sampling functionality throw the ``sample`` method::
"throw" should be "through".

Fix typo in introduction.rst

---

doc/metrics.rst
doc/user_guide.rst
doc/whats_new/v0.0.4.rst
imblearn/metrics/classification.py

closes #367 
Write documentation regarding the metrics when dealing with imbalanced dataset.

[MRG] DOC add metrics documentation in user guide

---

imblearn/utils/estimator_checks.py

use `set_random_state` instead of using the signature of the estimator

COSMIT use set_random_state in commmon test

---

imblearn/_version.py
setup.py

MAINT do not import imblearn in setup

---

conftest.py

MAINT add conftest to pass the docstring

---

doc/over_sampling.rst
imblearn/over_sampling/adasyn.py

Minor changes in docs

---

README.rst

Single char typo fix in README

---

imblearn/pipeline.py

DOC: improve documentation of pipeline

---

imblearn/ensemble/classifier.py

DOC: mention EasyEnsemble in BalancedBaggingClassifier

---

doc/whats_new/v0.0.4.rst
imblearn/combine/smote_enn.py
imblearn/combine/smote_tomek.py
imblearn/ensemble/balance_cascade.py
imblearn/over_sampling/smote.py
imblearn/under_sampling/prototype_generation/cluster_centroids.py
imblearn/under_sampling/prototype_selection/condensed_nearest_neighbour.py
imblearn/under_sampling/prototype_selection/instance_hardness_threshold.py
imblearn/under_sampling/prototype_selection/one_sided_selection.py
imblearn/utils/tests/test_validation.py
imblearn/utils/validation.py

BUG: clone estimator passed as attribute

---

doc/whats_new/v0.0.4.rst
imblearn/utils/tests/test_validation.py
imblearn/utils/validation.py

BUG: fix non deterministic result by always sorting sampling_strategy

---

doc/api.rst
doc/ensemble.rst
doc/whats_new/v0.0.4.rst
imblearn/ensemble/__init__.py
imblearn/ensemble/_classifier.py
imblearn/ensemble/_easy_ensemble.py
imblearn/ensemble/tests/test_easy_ensemble.py

closes #442 
Implement the EasyEnsembleClassifier as mentioned in the paper.

EHN: Create the EasyEnsembleClassifier

---

doc/whats_new/v0.0.4.rst
imblearn/over_sampling/base.py
imblearn/under_sampling/base.py

DOC: Fix the documentation of sampling_strategy as a float

---

doc/over_sampling.rst

Hey there,
Noticed this odd-sounding sentence while reading the docs today. Hope this is helpful.
Thanks for all your work on this library!

DOC: Fix a minor typo

---

doc/ensemble.rst

DOC: correct statement in Balanced Random Forest

---

doc/whats_new.rst
doc/whats_new/v0.5.rst
imblearn/__init__.py

MAINT: make import imblearn possible

---

imblearn/tests/test_pipeline.py

FIX: modify regex in pipeline testing to be more permissive

---

doc/over_sampling.rst

DOC fix smote reference in documentation

---

doc/whats_new/v0.5.rst
imblearn/over_sampling/_smote.py
imblearn/over_sampling/tests/test_smote.py

FIX properly set the default n_neighbours in SMOTE svm and borderline

---

doc/ensemble.rst
examples/model_selection/plot_validation_curve.py
imblearn/combine/_smote_enn.py
imblearn/combine/_smote_tomek.py
imblearn/ensemble/_bagging.py
imblearn/ensemble/_easy_ensemble.py
imblearn/ensemble/_forest.py
imblearn/over_sampling/_adasyn.py
imblearn/over_sampling/_smote.py
imblearn/under_sampling/_prototype_generation/_cluster_centroids.py
imblearn/under_sampling/_prototype_selection/_condensed_nearest_neighbour.py
imblearn/under_sampling/_prototype_selection/_edited_nearest_neighbours.py
imblearn/under_sampling/_prototype_selection/_instance_hardness_threshold.py
imblearn/under_sampling/_prototype_selection/_nearmiss.py
imblearn/under_sampling/_prototype_selection/_neighbourhood_cleaning_rule.py
imblearn/under_sampling/_prototype_selection/_one_sided_selection.py
imblearn/under_sampling/_prototype_selection/_tomek_links.py

DOC update several docsting

---

.gitignore
build_tools/circle/build_doc.sh
doc/bibtex/refs.bib
doc/combine.rst
doc/conf.py
doc/ensemble.rst
doc/metrics.rst
doc/over_sampling.rst
doc/references.rst
doc/under_sampling.rst
doc/user_guide.rst
imblearn/under_sampling/_prototype_selection/_tomek_links.py
setup.py

closes #634 
add sphinxcontib-bibtex to manage the reference page for us

MNT add sphinxcontrib-bibtex to manage citation

---

imblearn/ensemble/_bagging.py
imblearn/ensemble/_weight_boosting.py

closes #641 
Synchronize boosting algorithm

MNT synchronize boosting algorithm

---

doc/introduction.rst
doc/whats_new/v0.6.rst
imblearn/base.py
imblearn/over_sampling/_random_over_sampler.py
imblearn/over_sampling/_smote.py
imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
imblearn/utils/estimator_checks.py

Allows pandas series in/out for `y`

ENH allows pandas series in/out

---

azure-pipelines.yml
build_tools/azure/install.cmd
build_tools/azure/install.sh
imblearn/base.py
imblearn/ensemble/_bagging.py
imblearn/ensemble/_forest.py
imblearn/metrics/_classification.py
imblearn/over_sampling/_random_over_sampler.py
imblearn/over_sampling/_smote.py
imblearn/pipeline.py
imblearn/tests/test_common.py
imblearn/under_sampling/_prototype_generation/_cluster_centroids.py
imblearn/under_sampling/_prototype_generation/tests/test_cluster_centroids.py
imblearn/under_sampling/_prototype_selection/_nearmiss.py
imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
imblearn/utils/_validation.py
imblearn/utils/estimator_checks.py
imblearn/utils/testing.py
imblearn/utils/tests/test_estimator_checks.py
imblearn/utils/tests/test_validation.py

Fix the regression with scikit-learn 0.23

FIX fix regression scikit-learn 0.23

---

imblearn/utils/_show_versions.py
imblearn/utils/tests/test_show_versions.py

Fixes #686
Add joblib into show_versions function outputs

Add joblib into show version output

---

doc/common_pitfalls.rst
doc/user_guide.rst

closes #751 
Add a documentation package to show what not to do when resampling and emphasize the use of `Pipeline`.

DOC add common pitfalls regarding data leakage in sampling

---

imblearn/pipeline.py

Synchronize `Pipeline` and `make_pipeline` with 0.24

MNNT synchronize pipeline

---

README.rst

Add the black style badge

---

imblearn/utils/estimator_checks.py
imblearn/utils/tests/test_estimator_checks.py

Add additional tests for samplers handling:

TST add common test for string and nan

---

doc/developers_utils.rst

closes #657 
Add some documentation on how to make major and bug fixes releases.

DOC add release process

---

doc/introduction.rst

docs: fix typo and improve clarity in introduction

---

build_tools/circle/build_doc.sh
examples/api/plot_sampling_strategy_usage.py
examples/applications/plot_over_sampling_benchmark_lfw.py
examples/applications/plot_topic_classication.py
examples/combine/plot_comparison_combine.py
examples/datasets/plot_make_imbalance.py
examples/evaluation/plot_classification_report.py
examples/evaluation/plot_metrics.py
examples/model_selection/plot_validation_curve.py
examples/under-sampling/plot_comparison_under_sampling.py
examples/under-sampling/plot_illustration_nearmiss.py

Fix a couple of documentation glitches

DOC fixes some documentation glitches

---

.github/circleci-artifacts-redirector.yml

CI add CircleCI redirector

---

imblearn/metrics/pairwise.py
imblearn/tests/test_docstring_parameters.py
imblearn/utils/estimator_checks.py

Fix latest failures with scikit-learn 1.2

MAINT fix remaining failures with scikit-learn 1.2

---

azure-pipelines.yml

Update the OS version on the CIs.

MAINT update OS version on CIs

---

doc/conf.py
doc/whats_new/v0.10.rst
examples/api/plot_sampling_strategy_usage.py
examples/applications/plot_impact_imbalanced_classes.py
examples/applications/plot_over_sampling_benchmark_lfw.py
examples/ensemble/plot_comparison_ensemble_classifier.py
examples/evaluation/plot_classification_report.py
examples/model_selection/plot_validation_curve.py
examples/over-sampling/plot_comparison_over_sampling.py
examples/under-sampling/plot_comparison_under_sampling.py
examples/under-sampling/plot_illustration_nearmiss.py
imblearn/ensemble/_bagging.py
imblearn/ensemble/_easy_ensemble.py
imblearn/ensemble/_forest.py
imblearn/ensemble/_weight_boosting.py

Use the latest display and avoid `FutureWarning` in the documentation.
Include a couple of fixes in the documentation as well.

DOC make example works with latest scikit-learn

---

doc/over_sampling.rst

typo in docs

---

doc/install.rst

Fixed a typo regarding the conda install section

---

imblearn/base.py
imblearn/combine/_smote_enn.py
imblearn/combine/_smote_tomek.py
imblearn/datasets/_imbalance.py
imblearn/datasets/_zenodo.py
imblearn/ensemble/_bagging.py
imblearn/ensemble/_easy_ensemble.py
imblearn/ensemble/_forest.py
imblearn/ensemble/_weight_boosting.py
imblearn/ensemble/tests/test_bagging.py
imblearn/keras/_generator.py
imblearn/metrics/_classification.py
imblearn/over_sampling/_adasyn.py
imblearn/over_sampling/_random_over_sampler.py
imblearn/over_sampling/_smote/base.py
imblearn/over_sampling/_smote/cluster.py
imblearn/over_sampling/_smote/filter.py
imblearn/tensorflow/_generator.py
imblearn/under_sampling/_prototype_generation/_cluster_centroids.py
imblearn/under_sampling/_prototype_selection/_condensed_nearest_neighbour.py
imblearn/under_sampling/_prototype_selection/_edited_nearest_neighbours.py
imblearn/under_sampling/_prototype_selection/_instance_hardness_threshold.py
imblearn/under_sampling/_prototype_selection/_nearmiss.py
imblearn/under_sampling/_prototype_selection/_neighbourhood_cleaning_rule.py
imblearn/under_sampling/_prototype_selection/_one_sided_selection.py
imblearn/under_sampling/_prototype_selection/_random_under_sampler.py
imblearn/under_sampling/_prototype_selection/_tomek_links.py

Remove the possibility to pass position arguments after the end of the deprecation cycle.

MAINT remove possibility to pass by position

---

examples/api/plot_sampling_strategy_usage.py

Minor fixes to documentation strings

DOC fix typo in an example

---

doc/introduction.rst

Corrected "level" to plural "levels" in "We illustrate the effect of training a linear SVM classifier with different levels of class balancing."
Corrected "level" to plural "levels" in "We illustrate the effect of training a linear SVM classifier with different levels of class balancing."

[MRG] Update introduction.rst

---

setup.cfg

Target py38 in flake8

---

doc/whats_new/v0.12.rst
imblearn/over_sampling/tests/test_random_over_sampler.py
imblearn/under_sampling/_prototype_selection/tests/test_random_under_sampler.py
imblearn/utils/_validation.py

closes #1055 
I don't have a better fix than special casing this one.

FIX handle full NaT columns properly in Random*Sampler

---

doc/under_sampling.rst
doc/whats_new/v0.12.rst
examples/applications/plot_outlier_rejections.py
imblearn/ensemble/tests/test_bagging.py
imblearn/tests/test_docstring_parameters.py
imblearn/tests/test_pipeline.py

This should solve some CIs errors linked to some deprecation.

MAINT avoid warning deprecation sklearn 1.5
